AWSTemplateFormatVersion: '2010-09-09'
Description: Setup AWS Service Catalog Product Only

Parameters:
  PortfolioId:
    Type: String
    Description: The ID of the existing portfolio
  ArtifactUrl:
    Type: String
    Description: S3 URL to the product's CloudFormation template

Resources:
  Product:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: HelloWorldProduct
      Owner: BM
      Description: A simple HelloWorld SC product using a CloudFormation template
      ProvisioningArtifactParameters:
        - Name: v1
          Type: CLOUD_FORMATION_TEMPLATE
          Description: First version
          Info:
            LoadTemplateFromURL: !Ref ArtifactUrl
