AWSTemplateFormatVersion: '2010-09-09'
Description: Setup AWS Service Catalog Product and Share across the Organization

Parameters:
  PortfolioId:
    Type: String
    Description: The ID of the existing portfolio
  ArtifactUrl:
    Type: String
    Description: S3 URL to the product's CloudFormation template or Terraform tar.gz
  RoleArn:
    Type: String
    Description: IAM Role ARN to be used as a launch constraint
  OrgId:
    Type: String
    Description: AWS Organization ID

Resources:

  Product:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: HelloWorldProduct
      Owner: BM
      Description: A simple HelloWorld SC product with a Terraform tarball
      ProvisioningArtifactParameters:
        - Name: v1
          Type: CLOUD_FORMATION_TEMPLATE
          Description: First version
          Info:
            LoadTemplateFromURL: !Ref ArtifactUrl

  PortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref Product

  LaunchConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref Product
      RoleArn: !Ref RoleArn

  PortfolioShare:
    Type: AWS::ServiceCatalog::PortfolioShare
    Properties:
      PortfolioId: !Ref PortfolioId
      OrganizationNode:
        Type: ORGANIZATION
        Value: !Ref OrgId
