AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 Bucket configured for static website hosting

Parameters:
  BucketName:
    Type: String
    Description: Enter a globally unique name for the S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Description: URL of the static website
    Value: !Sub "http://${BucketName}.s3-website-${AWS::Region}.amazonaws.com"
